---
title: "Change Analysis"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)
library(readr)

```

```{r, echo=FALSE}
us_states_raw <- read_csv("~/projects/covid-19-data/us-states.csv",
                      col_types = cols(date = col_date(format = "%Y-%m-%d")))

#us_states$state <- as.factor(as.factor(us_states$state))
#us_states <- mutate_if(us_states, is.character, as.factor)

df_us_states <- us_states_raw %>%
  mutate_if(is.character, as.factor) 
  
# prep variable scale for Y axis
max_y <- ceiling(max(log2(df_us_states['cases'])))
powers_of_2 = 2 ** (1:max_y)

```

```{r, echo=FALSE}
# compute lag so that we can see actual change day by day
df_us_states <- df_us_states %>%
  group_by(state) %>%
  mutate(delta_cases =  cases - lag(cases, order_by=date), 
         delta_deaths = deaths - lag(deaths,order_by=date))

```


```{r, fig.width=12, fig.height=10, echo=FALSE, message=FALSE}
p <- ggplot(subset(df_us_states, !is.na(delta_cases)), aes(x=date, y=delta_cases)) +
  geom_col() + 
  facet_wrap( . ~ state) +
  ggtitle("Covid change in cases by state - linear") +
  theme(strip.text.x = element_text(size = 9)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
 print(p)

```

```{r, fig.width=12, fig.height=10, echo=FALSE, message=FALSE}
p <- ggplot(subset(df_us_states, !is.na(delta_deaths)), aes(x=date, y=delta_deaths)) +
  geom_col() + 
  facet_wrap( . ~ state) +
  ggtitle("Covid change in deaths by state - linear") +
  theme(strip.text.x = element_text(size = 9)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
 print(p)

```

## Change over Cumuluative Sum

```{r, fig.width=12, fig.height=10, echo=FALSE, message=FALSE, warning=FALSE}
p <- ggplot(df_us_states, aes(x=cases, y=delta_cases)) +
  geom_line() + 
  facet_wrap( . ~ state) +
  scale_x_continuous(trans='log10') +
  #scale_y_continuous(trans='log10') +
  ggtitle("Covid cases rate of change by state - linear/log-x") +
  #theme(axis.text.y = element_text(size = 6)) +
  theme(strip.text.x = element_text(size = 9)) +
  theme(strip.text.y = element_text(size = 9)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
print(p)

```
## Log of Change Over Cumulative Sum

An experimental view, looking for way to measure when the rate of change has dropped.
Its too granular still, i need to aggegrate it at weekly intervals possibly.

```{r, fig.width=12, fig.height=10, echo=FALSE, message=FALSE, warning=FALSE}
#filtered_cases <- subset(df_us_states, cases > 0)
pq <- ggplot(df_us_states, aes(x=cases, y=delta_cases)) +
  geom_line() + 
  facet_wrap( . ~ state) +
  scale_x_continuous(trans='log10') +
  scale_y_continuous(trans='log10') +
  ggtitle("Covid cases rate of change by state - log/log") +
  #theme(axis.text.y = element_text(size = 6)) +
  theme(strip.text.x = element_text(size = 9)) +
  theme(strip.text.y = element_text(size = 9)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
print(pq)

```

```{r, fig.width=12, fig.height=10, echo=FALSE, message=FALSE, warning=FALSE}
#filtered_cases <- subset(df_us_states, cases > 0)
pq <- ggplot(df_us_states, aes(x=deaths, y=delta_deaths)) +
  geom_line() + 
  facet_wrap( . ~ state) +
  scale_x_continuous(trans='log10') +
  scale_y_continuous(trans='log10') +
  ggtitle("Covid deaths rate of change by state") +
  #theme(axis.text.y = element_text(size = 6)) +
  theme(strip.text.x = element_text(size = 9)) +
  theme(strip.text.y = element_text(size = 9)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) 
print(pq)

```
